/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zerohungerapp;

import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nerijus Kmitas
 * Student ID x24170232
 */

//This is main GUI for managing donations
//Contains input for donor details, donation details, profile picture
//and buttons to save, search, print, and delete records

public class DonationScreen extends javax.swing.JFrame {

    private HomeScreen parent;

    //It is holding the path to profile picture selected by current donor
    private String currentImagePath = "";

    // Logger for any potential errors
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DonationScreen.class.getName());

    private List<Donation> donations;

    //Constructors
    public DonationScreen(HomeScreen inParent) {
        initComponents();
        parent = inParent;

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        //When the window closes show the parent (home) page again
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                parent.setVisible(true);
                dispose();

            }
        });
        //Initialize donations reference from managerr
        donations = DonationManager.getDonations();
    }

    //Constructor
    public DonationScreen() {
        initComponents();
        donations = DonationManager.getDonations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personalDetailsTitle = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        donationDetailsTitle = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        typeOfFoodLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        typeOfFoodText = new javax.swing.JTextField();
        quantityText = new javax.swing.JTextField();
        printTheListButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfDonationsTextArea = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        profilePictureButton = new javax.swing.JButton();
        imageIconLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personalDetailsTitle.setText("PERSONAL DETAILS");
        personalDetailsTitle.setToolTipText("");
        personalDetailsTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLabel.setText("Enter your Name:");

        LastNameLabel.setText("Enter your Last Name:");

        emailLabel.setText("Enter your E-mail Address:");

        phoneLabel.setText("Enter your Phone Number:");

        donationDetailsTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        donationDetailsTitle.setText("DONATION DETAILS");
        donationDetailsTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dateLabel.setText("Enter Date:");

        typeOfFoodLabel.setText("Type of Food:");

        quantityLabel.setText("Enter Quantity:");

        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });

        printTheListButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printTheListButton.setText("Print the List");
        printTheListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTheListButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        goBackButton.setText("Back to Home Screen");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        listOfDonationsTextArea.setColumns(20);
        listOfDonationsTextArea.setRows(5);
        listOfDonationsTextArea.setText("List of Donors and Donations...");
        jScrollPane1.setViewportView(listOfDonationsTextArea);

        searchButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        profilePictureButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        profilePictureButton.setText("Add Profile Picture");
        profilePictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictureButtonActionPerformed(evt);
            }
        });

        imageIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageIconLabel.setText("Image Icon");
        imageIconLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        imageIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageIconLabel.setPreferredSize(new java.awt.Dimension(61, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printTheListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profilePictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeOfFoodLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantityLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateText)
                            .addComponent(typeOfFoodText)
                            .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personalDetailsTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(donationDetailsTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(goBackButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personalDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(imageIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(donationDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabel)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeOfFoodLabel)
                            .addComponent(typeOfFoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLabel)
                            .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profilePictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(printTheListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        //Personal fields
        String name = nameText.getText().trim();
        String lastName = lastNameText.getText().trim();
        String email = emailText.getText().trim();
        String phone = phoneText.getText().trim();

        // Donation fields
        String date = dateText.getText().trim();
        String foodType = typeOfFoodText.getText().trim();
        String quantityStr = quantityText.getText().trim();

        //Validation of every input
        //Name section can't be left empty
        if (name.isEmpty() || lastName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name and Last Name cannot be empty.");
            return;
        }

        //Email address has to contain '@' sign
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email is not valid. It must contain '@'.");
            return;
        }

        //Phone number has to contain integer numbers only
        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number cannot be empty.");
            return;
        }
        try {
            Long.valueOf(phone);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phone number must contain only numbers.");
            return;
        }

        //Data format is restricted to this type: "dd/mm/yy"
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        sdf.setLenient(false);       // strict parsing
        try {
            sdf.parse(date);         //throws ParseException if format is wrong
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Date must be in the format DD/MM/YY.");
            return;
        }

        //Food type section can't be left empty
        if (foodType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Food Type cannot be empty.");
            return;
        }

        //Quantity has to be a integer number
        int quantity;
        try {
            quantity = Integer.parseInt(quantityStr);
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be a number greater than 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a valid number.");
            return;
        }

        //Used to create donor and set the chosen image path
        Donor donor = new Donor(name, lastName, email, phone);
        //currentImagePath will be set by profilePictureButton
        donor.setImagePath(currentImagePath);

        //Create a donation
        Donation donation = new Donation(donor, date, foodType, quantity);

        //Add the donation to list in memory and save it to the file
        DonationManager.addDonation(donation);
        DonationManager.saveToFile();

        JOptionPane.showMessageDialog(this, "Donation saved successfully!");

        //It will clear UI inputs
        nameText.setText("");
        lastNameText.setText("");
        emailText.setText("");
        phoneText.setText("");
        dateText.setText("");
        typeOfFoodText.setText("");
        quantityText.setText("");
        currentImagePath = "";
        imageIconLabel.setIcon(null);
        imageIconLabel.setText("Image Icon");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void printTheListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTheListButtonActionPerformed
        //After pressing the button will print all the list to the textArea
        listOfDonationsTextArea.setText("");

        if (DonationManager.getDonations().isEmpty()) {
            listOfDonationsTextArea.setText("No donations recorded yet!");
            return;
        }

        for (Donation d : DonationManager.getDonations()) {
            listOfDonationsTextArea.append(
                    "Donation ID: " + d.getDonationId() + "\n"
                    + "Donor: " + d.getDonor().getName() + " " + d.getDonor().getLastName() + "\n"
                    + "Email: " + d.getDonor().getEmail() + "\n"
                    + "Phone: " + d.getDonor().getPhone() + "\n"
                    + "Date: " + d.getDate() + "\n"
                    + "Food Type: " + d.getTypeOfFood() + "\n"
                    + "Quantity: " + d.getQuantity() + "\n"
                    + "-----------------------------------------\n"
            );
        }
    }//GEN-LAST:event_printTheListButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //After pressing button donation will be deleted by user ID
        String idStr = JOptionPane.showInputDialog(this, "Enter Donation ID to delete:");
        if (idStr != null && !idStr.trim().isEmpty()) {
            try {
                int id = Integer.parseInt(idStr.trim());
                boolean deleted = DonationManager.deleteDonation(id);
                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Donation deleted successfully!");
                    listOfDonationsTextArea.setText(""); // clear or refresh list
                } else {
                    JOptionPane.showMessageDialog(this, "Donation ID not found.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Donation ID.");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //Search by donor name and display results including the profile picture that was saved
        String name = JOptionPane.showInputDialog(this, "Enter Donor Name to search:");
        if (name != null && !name.trim().isEmpty()) {
            ArrayList<Donation> results = DonationManager.searchDonationsByDonorName(name.trim());
            if (results.isEmpty()) {
                listOfDonationsTextArea.setText("No donations found for donor: " + name);
                imageIconLabel.setIcon(null);
                imageIconLabel.setText("Image Icon");
            } else {
                listOfDonationsTextArea.setText("");
                for (Donation d : results) {
                    listOfDonationsTextArea.append(d.toString() + "\n-----\n");

                    //Restore the profile picture for the donor if it is available
                    //After pressing search button it will restore saved profile picture of the Donor
                    String path = d.getDonor().getImagePath();
                    if (path != null && !path.isEmpty()) {
                        File f = new File(path);
                        if (f.exists()) {
                            ImageIcon icon = new ImageIcon(path);
                            Image img = icon.getImage().getScaledInstance(92, 83, Image.SCALE_SMOOTH);
                            imageIconLabel.setIcon(new ImageIcon(img));
                            imageIconLabel.setText("");
                        } else {
                            //File is not found
                            imageIconLabel.setIcon(null);
                            imageIconLabel.setText("Image not found!");
                        }
                    } else {
                        imageIconLabel.setIcon(null);
                        imageIconLabel.setText("Image Icon");

                    }
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void profilePictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictureButtonActionPerformed
        //Profile picture selection dialog. It will store chosen patch to currentImagePath
        //and will show preview

        JFileChooser fileChooser = new JFileChooser();

        //User is allowed to upload only image file as described below
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files", "jpg", "jpeg", "png", "gif", "webp");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            //Store path so it can be later saved with Donor
            currentImagePath = selectedFile.getAbsolutePath();

            //Create icon and resize it to preview
            ImageIcon imageIcon = new ImageIcon(currentImagePath);
            Image originalImage = imageIcon.getImage();

            //Resize it to match my window of (92 width by 83 height)
            Image resizedImage = originalImage.getScaledInstance(
                    92, 83, Image.SCALE_SMOOTH);
            
            //Show image preview in the label
            imageIconLabel.setIcon(new ImageIcon(resizedImage));
        }
    }//GEN-LAST:event_profilePictureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DonationScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel donationDetailsTitle;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel imageIconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextArea listOfDonationsTextArea;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel personalDetailsTitle;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton printTheListButton;
    private javax.swing.JButton profilePictureButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel typeOfFoodLabel;
    private javax.swing.JTextField typeOfFoodText;
    // End of variables declaration//GEN-END:variables
}
