/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zerohungerapp;

/**
 *
 * @author Tiyko - Ionut Ciobanu
 */
public class RestaurantScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RestaurantScreen.class.getName());

    /**
     * Creates new form RestaurantScreen
     */
    public RestaurantScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        restaurantDetailsLabel = new javax.swing.JLabel();
        restaurantNameLabel = new javax.swing.JLabel();
        restaurantAddressLabel = new javax.swing.JLabel();
        restaurantEmailAddressLabel = new javax.swing.JLabel();
        restaurantPhoneNumberLabel = new javax.swing.JLabel();
        collectionDetailsLabel = new javax.swing.JLabel();
        collectionDateLabel = new javax.swing.JLabel();
        collectionTimeLabel = new javax.swing.JLabel();
        collectionFoodTypeLabel = new javax.swing.JLabel();
        collectionQuantityLabel = new javax.swing.JLabel();
        restaurantNameField = new javax.swing.JTextField();
        restaurantAddressField = new javax.swing.JTextField();
        restaurantEmailAddressField = new javax.swing.JTextField();
        restaurantPhoneNumberField = new javax.swing.JTextField();
        collectionDateField = new javax.swing.JTextField();
        collectionTimeField = new javax.swing.JTextField();
        collectionQuantityField = new javax.swing.JTextField();
        collectionFoodTypeField = new javax.swing.JTextField();
        addDetailsButton = new javax.swing.JButton();
        removeFromScheduleListButton = new javax.swing.JButton();
        scheduleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scheduleList = new javax.swing.JList<>();
        goBackButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restaurantDetailsLabel.setText("Restaurant Details");

        restaurantNameLabel.setText("Name:");

        restaurantAddressLabel.setText("Address:");

        restaurantEmailAddressLabel.setText("Email:");

        restaurantPhoneNumberLabel.setText("Phone No:");

        collectionDetailsLabel.setText("Collection Details");

        collectionDateLabel.setText("Date:");

        collectionTimeLabel.setText("Time:");

        collectionFoodTypeLabel.setText("Food Type:");

        collectionQuantityLabel.setText("Food Quantity:");

        restaurantNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantNameFieldActionPerformed(evt);
            }
        });

        restaurantAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantAddressFieldActionPerformed(evt);
            }
        });

        restaurantEmailAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantEmailAddressFieldActionPerformed(evt);
            }
        });

        restaurantPhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantPhoneNumberFieldActionPerformed(evt);
            }
        });

        collectionDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionDateFieldActionPerformed(evt);
            }
        });

        collectionTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionTimeFieldActionPerformed(evt);
            }
        });

        collectionQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionQuantityFieldActionPerformed(evt);
            }
        });

        collectionFoodTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionFoodTypeFieldActionPerformed(evt);
            }
        });

        addDetailsButton.setText("Add");
        addDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetailsButtonActionPerformed(evt);
            }
        });

        removeFromScheduleListButton.setText("Remove");
        removeFromScheduleListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromScheduleListButtonActionPerformed(evt);
            }
        });

        scheduleLabel.setText("Schedule:");

        scheduleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(scheduleList);

        goBackButton.setText("Back to Home Screen");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restaurantNameLabel)
                            .addComponent(restaurantAddressLabel)
                            .addComponent(restaurantEmailAddressLabel)
                            .addComponent(restaurantPhoneNumberLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(restaurantDetailsLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(restaurantNameField)
                                            .addComponent(restaurantAddressField)
                                            .addComponent(restaurantEmailAddressField)
                                            .addComponent(restaurantPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(collectionQuantityLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(collectionQuantityField))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(collectionFoodTypeLabel)
                                                .addGap(38, 38, 38)
                                                .addComponent(collectionFoodTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(collectionDateLabel)
                                                    .addComponent(collectionTimeLabel))
                                                .addGap(67, 67, 67)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(collectionDateField)
                                                    .addComponent(collectionTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(removeFromScheduleListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(goBackButton)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(addDetailsButton)))
                                        .addContainerGap(24, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduleLabel)
                        .addGap(419, 419, 419)
                        .addComponent(collectionDetailsLabel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collectionDetailsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantNameLabel)
                    .addComponent(collectionDateLabel)
                    .addComponent(collectionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantAddressLabel)
                    .addComponent(collectionTimeLabel)
                    .addComponent(collectionTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantEmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantEmailAddressLabel)
                    .addComponent(collectionFoodTypeLabel)
                    .addComponent(collectionFoodTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantPhoneNumberLabel)
                    .addComponent(collectionQuantityLabel)
                    .addComponent(collectionQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scheduleLabel)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeFromScheduleListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restaurantNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaurantNameFieldActionPerformed

    private void restaurantAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaurantAddressFieldActionPerformed

    private void restaurantEmailAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantEmailAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaurantEmailAddressFieldActionPerformed

    private void restaurantPhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantPhoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaurantPhoneNumberFieldActionPerformed

    private void collectionDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectionDateFieldActionPerformed

    private void collectionTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectionTimeFieldActionPerformed

    private void collectionFoodTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionFoodTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectionFoodTypeFieldActionPerformed

    private void collectionQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectionQuantityFieldActionPerformed

    private void addDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDetailsButtonActionPerformed

    private void removeFromScheduleListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromScheduleListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeFromScheduleListButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen().setVisible(true);  // open Home Screen
        dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RestaurantScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDetailsButton;
    private javax.swing.JTextField collectionDateField;
    private javax.swing.JLabel collectionDateLabel;
    private javax.swing.JLabel collectionDetailsLabel;
    private javax.swing.JTextField collectionFoodTypeField;
    private javax.swing.JLabel collectionFoodTypeLabel;
    private javax.swing.JTextField collectionQuantityField;
    private javax.swing.JLabel collectionQuantityLabel;
    private javax.swing.JTextField collectionTimeField;
    private javax.swing.JLabel collectionTimeLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton removeFromScheduleListButton;
    private javax.swing.JTextField restaurantAddressField;
    private javax.swing.JLabel restaurantAddressLabel;
    private javax.swing.JLabel restaurantDetailsLabel;
    private javax.swing.JTextField restaurantEmailAddressField;
    private javax.swing.JLabel restaurantEmailAddressLabel;
    private javax.swing.JTextField restaurantNameField;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JTextField restaurantPhoneNumberField;
    private javax.swing.JLabel restaurantPhoneNumberLabel;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JList<String> scheduleList;
    // End of variables declaration//GEN-END:variables
}
